Repository kth-cdate-courses/DD2480, pull requests merged in 2023-01, with the labels that each got.

#23 fix: Basic setup #2
  decide/src/main/java/org/example/Decide.java
  decide/src/main/java/org/example/InitialSettings.java
  decide/src/main/java/org/example/LogicalOperator.java
Labels: improvement

#30 Fix GitHub action file
  .github/workflows/testing.yml
Labels: bug

#25 Condition 0 implementation
  decide/src/main/java/org/example/Decide.java
  decide/src/main/java/org/example/InitialSettings.java
Labels: feature

#26 Condition 7 implementation
  decide/src/main/java/org/example/Decide.java
Labels: feature

#27 Condition 12 implementation
  decide/src/main/java/org/example/Decide.java
Labels: feature

#32 Erik/feat/5 add condition3
  decide/src/main/java/org/example/Decide.java
  decide/src/main/java/org/example/InitialSettings.java
Labels: feature

#33 feat: implement condition 10
  decide/src/main/java/org/example/Decide.java
Labels: feature

#37 refactor: move inner class Point to separete class
  decide/src/main/java/org/example/Decide.java
  decide/src/main/java/org/example/InitialSettings.java
  decide/src/main/java/org/example/Point.java
Labels: refactor

#28 Add CMV
  decide/src/main/java/org/example/Decide.java
Labels: feature

#46 Add two unit tests for condition0
  decide/decide.iml
  decide/src/test/java/org/example/DecideTest.java
Labels: test

#48 FUV validation function
  decide/src/main/java/org/example/Decide.java
Labels: feature

#49 Implement condition 14
  decide/src/main/java/org/example/Decide.java
Labels: feature

#34 Condition 6 implementation
  decide/src/main/java/org/example/Decide.java
  decide/src/main/java/org/example/Point.java
Labels: feature

#43 Condition 8 method #10
  decide/src/main/java/org/example/Decide.java
Labels: feature

#44 Condition 13 method #14
  decide/src/main/java/org/example/Decide.java
Labels: feature

#45 Create method for PUM #18
  decide/src/main/java/org/example/Decide.java
Labels: feature

#70 Pauline/feat/7 condition5
  decide/src/main/java/org/example/Decide.java
Labels: feature

#71 Condition 11 method #12
  decide/src/main/java/org/example/Decide.java
Labels: feature

#72 Add unit tests for condition1
  decide/src/test/java/org/example/DecideTest.java
Labels: test

#73 Add unit test for condition2
  decide/src/test/java/org/example/DecideTest.java
Labels: test

#78 Add unit test for condition7
  decide/src/test/java/org/example/DecideTest.java
Labels: test

#52 feat: implement condition 2 #4
  decide/src/main/java/org/example/Decide.java
Labels: feature

#53 feat: implement condition 9 #11
  decide/src/main/java/org/example/Decide.java
Labels: feature

#88 Add unit tests for condition9
  decide/src/test/java/org/example/DecideTest.java
Labels: test

#83 Add unit test for condition11
  decide/src/test/java/org/example/DecideTest.java
Labels: test

#85 Add unit test for condition12
  decide/src/test/java/org/example/DecideTest.java
Labels: test

#86 Add unit test for condition13
  decide/src/test/java/org/example/DecideTest.java
Labels: test

#87 Add unit tests for condition14
  decide/src/test/java/org/example/DecideTest.java
Labels: test

#108 Fix failing true-test for condition 2
  decide/src/test/java/org/example/DecideTest.java
Labels: bug

#109 Fix failing true-test for condition 4
  decide/src/main/java/org/example/Decide.java
Labels: bug

#105 Fix edge case and crash in method getIntersectPoint
  decide/src/main/java/org/example/Decide.java
  decide/src/main/java/org/example/Point.java
Labels: bug

#114 Fix failing true-test for condition 9
  decide/src/test/java/org/example/DecideTest.java
Labels: bug

#126 Fix failing false-test for condition 9
  decide/src/main/java/org/example/Decide.java
Labels: bug

#107 feat: Compute Final Unlocking Vector #96
  decide/src/main/java/org/example/Decide.java
Labels: feature

#120 Pauline/fix/69 undefined angle handling
  decide/src/main/java/org/example/Decide.java
  decide/src/main/java/org/example/Point.java
Labels: bug

#127 Fix: issue #101 add comments to condition0
  decide/src/test/java/org/example/DecideTest.java
Labels: documentation

#128 Fix: issue #110 add comments to condition1
  decide/src/test/java/org/example/DecideTest.java
Labels: documentation

#129 Fix: issue #111 add comment to test for condition2
  decide/src/test/java/org/example/DecideTest.java
Labels: documentation

#130 Fix: issue #112 add comment to tests condition3
  decide/src/test/java/org/example/DecideTest.java
Labels: documentation
